# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowDBAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 421, 903))
        self.frame_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.line_49 = QtWidgets.QFrame(self.frame_4)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.verticalLayout_2.addWidget(self.line_49)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.max_temp_bico_injetor = QtWidgets.QLineEdit(self.frame_4)
        self.max_temp_bico_injetor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.max_temp_bico_injetor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.max_temp_bico_injetor.setAlignment(QtCore.Qt.AlignCenter)
        self.max_temp_bico_injetor.setObjectName("max_temp_bico_injetor")
        self.verticalLayout_2.addWidget(self.max_temp_bico_injetor)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.max_temp_arrefecimento = QtWidgets.QLineEdit(self.frame_4)
        self.max_temp_arrefecimento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.max_temp_arrefecimento.setAlignment(QtCore.Qt.AlignCenter)
        self.max_temp_arrefecimento.setObjectName("max_temp_arrefecimento")
        self.verticalLayout_2.addWidget(self.max_temp_arrefecimento)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.max_temp_combustivel = QtWidgets.QLineEdit(self.frame_4)
        self.max_temp_combustivel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.max_temp_combustivel.setAlignment(QtCore.Qt.AlignCenter)
        self.max_temp_combustivel.setObjectName("max_temp_combustivel")
        self.verticalLayout_2.addWidget(self.max_temp_combustivel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.max_temp_Intercooler = QtWidgets.QLineEdit(self.frame_4)
        self.max_temp_Intercooler.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.max_temp_Intercooler.setAlignment(QtCore.Qt.AlignCenter)
        self.max_temp_Intercooler.setObjectName("max_temp_Intercooler")
        self.verticalLayout_2.addWidget(self.max_temp_Intercooler)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.line_50 = QtWidgets.QFrame(self.frame_4)
        self.line_50.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.verticalLayout_2.addWidget(self.line_50)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.limite_min_inf_cilindro = QtWidgets.QLineEdit(self.frame_4)
        self.limite_min_inf_cilindro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.limite_min_inf_cilindro.setAlignment(QtCore.Qt.AlignCenter)
        self.limite_min_inf_cilindro.setObjectName("limite_min_inf_cilindro")
        self.verticalLayout_2.addWidget(self.limite_min_inf_cilindro)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.limite_min_sup_cilindro = QtWidgets.QLineEdit(self.frame_4)
        self.limite_min_sup_cilindro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.limite_min_sup_cilindro.setAlignment(QtCore.Qt.AlignCenter)
        self.limite_min_sup_cilindro.setObjectName("limite_min_sup_cilindro")
        self.verticalLayout_2.addWidget(self.limite_min_sup_cilindro)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.line_51 = QtWidgets.QFrame(self.frame_4)
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.verticalLayout_2.addWidget(self.line_51)
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.data_inicial = QtWidgets.QLineEdit(self.frame_4)
        self.data_inicial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.data_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.data_inicial.setObjectName("data_inicial")
        self.verticalLayout_2.addWidget(self.data_inicial)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.data_final = QtWidgets.QLineEdit(self.frame_4)
        self.data_final.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.data_final.setAlignment(QtCore.Qt.AlignCenter)
        self.data_final.setObjectName("data_final")
        self.verticalLayout_2.addWidget(self.data_final)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.temp_cilindro = QtWidgets.QCheckBox(self.frame)
        self.temp_cilindro.setGeometry(QtCore.QRect(10, 10, 191, 17))
        self.temp_cilindro.setObjectName("temp_cilindro")
        self.save_to_csv = QtWidgets.QCheckBox(self.frame)
        self.save_to_csv.setGeometry(QtCore.QRect(10, 50, 161, 17))
        self.save_to_csv.setObjectName("save_to_csv")
        self.max_min = QtWidgets.QCheckBox(self.frame)
        self.max_min.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.max_min.setObjectName("max_min")
        self.ranque_arrefecimento = QtWidgets.QCheckBox(self.frame)
        self.ranque_arrefecimento.setGeometry(QtCore.QRect(10, 70, 211, 17))
        self.ranque_arrefecimento.setObjectName("ranque_arrefecimento")
        self.grafico_temperatura = QtWidgets.QCheckBox(self.frame)
        self.grafico_temperatura.setGeometry(QtCore.QRect(120, 30, 301, 17))
        self.grafico_temperatura.setObjectName("grafico_temperatura")
        self.analise_limites_inferiores = QtWidgets.QCheckBox(self.frame)
        self.analise_limites_inferiores.setGeometry(QtCore.QRect(210, 10, 151, 17))
        self.analise_limites_inferiores.setObjectName("analise_limites_inferiores")
        self.analise_temperatura_media = QtWidgets.QCheckBox(self.frame)
        self.analise_temperatura_media.setGeometry(QtCore.QRect(180, 50, 171, 17))
        self.analise_temperatura_media.setObjectName("analise_temperatura_media")
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.line_52 = QtWidgets.QFrame(self.frame_4)
        self.line_52.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.verticalLayout_2.addWidget(self.line_52)
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.btn_Exec = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.btn_Exec.setFont(font)
        self.btn_Exec.setObjectName("btn_Exec")
        self.verticalLayout_2.addWidget(self.btn_Exec)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout_2.setStretch(10, 1)
        self.verticalLayout_2.setStretch(11, 1)
        self.verticalLayout_2.setStretch(12, 1)
        self.verticalLayout_2.setStretch(13, 1)
        self.verticalLayout_2.setStretch(14, 1)
        self.verticalLayout_2.setStretch(15, 1)
        self.verticalLayout_2.setStretch(16, 1)
        self.verticalLayout_2.setStretch(17, 1)
        self.verticalLayout_2.setStretch(18, 1)
        self.verticalLayout_2.setStretch(19, 1)
        self.verticalLayout_2.setStretch(20, 1)
        self.verticalLayout_2.setStretch(21, 1)
        self.verticalLayout_2.setStretch(22, 1)
        self.verticalLayout_2.setStretch(23, 1)
        self.verticalLayout_2.setStretch(24, 1)
        self.verticalLayout_2.setStretch(25, 1)
        self.verticalLayout_2.setStretch(26, 1)
        self.verticalLayout_2.setStretch(27, 1)
        self.verticalLayout_2.setStretch(28, 1)
        self.verticalLayout_2.setStretch(29, 1)
        self.verticalLayout_2.setStretch(30, 1)
        self.verticalLayout_2.setStretch(31, 1)
        self.verticalLayout_2.setStretch(32, 1)
        self.verticalLayout_2.setStretch(33, 1)
        self.verticalLayout_2.setStretch(34, 1)
        self.verticalLayout_2.setStretch(35, 1)
        self.verticalLayout_2.setStretch(36, 20)
        self.verticalLayout_2.setStretch(37, 1)
        self.verticalLayout_2.setStretch(38, 1)
        self.verticalLayout_2.setStretch(39, 1)
        self.verticalLayout_2.setStretch(40, 1)
        self.gridLayout_55.addWidget(self.frame_4, 0, 0, 2, 1, QtCore.Qt.AlignVCenter)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.path = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.path.setFont(font)
        self.path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.path.setObjectName("path")
        self.horizontalLayout_2.addWidget(self.path)
        self.salvaDir = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.salvaDir.setFont(font)
        self.salvaDir.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.salvaDir.setObjectName("salvaDir")
        self.horizontalLayout_2.addWidget(self.salvaDir)
        self.gridLayout_55.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInicio.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Limites Superiores"))
        self.label_2.setText(_translate("MainWindow", "Temperatura do Bico Injetor"))
        self.label_3.setText(_translate("MainWindow", "Temperatura de Arrefecimento"))
        self.label_4.setText(_translate("MainWindow", "Temperatura do Combustível"))
        self.label_5.setText(_translate("MainWindow", "Temperatura do Intercooler"))
        self.label_11.setText(_translate("MainWindow", "Limites Inferior"))
        self.label_6.setText(_translate("MainWindow", "Limite mínimo de inferior temperatura do cilindro"))
        self.label_7.setText(_translate("MainWindow", "Limite mínimo de superior temperatura do cilindro"))
        self.label_13.setText(_translate("MainWindow", "Datas para análise"))
        self.label_9.setText(_translate("MainWindow", "Data inicial para análise - (AAAA/MM/DD hh:mm:ss.fff)"))
        self.label_12.setText(_translate("MainWindow", "Data final para análise - (AAAA/MM/DD hh:mm:ss.fff)"))
        self.label_14.setText(_translate("MainWindow", "Tipos de análise"))
        self.temp_cilindro.setText(_translate("MainWindow", "Tempo dos cilindros acima da média"))
        self.save_to_csv.setText(_translate("MainWindow", "Salvar dados na tabelas CSV"))
        self.max_min.setText(_translate("MainWindow", "Máximo e mínimo"))
        self.ranque_arrefecimento.setText(_translate("MainWindow", "Ranque dos geradores - Arrefecimento"))
        self.grafico_temperatura.setText(_translate("MainWindow", "Gráfico combinado com temperatura dos líquidos"))
        self.analise_limites_inferiores.setText(_translate("MainWindow", "Analise Limites Inferiores"))
        self.analise_temperatura_media.setText(_translate("MainWindow", "Análise da temperatura média"))
        self.btn_Exec.setText(_translate("MainWindow", "Executar"))
        self.salvaDir.setText(_translate("MainWindow", "Selecionar Pasta"))
        self.menuInicio.setTitle(_translate("MainWindow", "Inicio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
